### ISSUE TITLE
Adding the calculator app

### ISSUE THREAD

**Issue by betatim** [binder-examples/appmode#1]
What do people think about adding in the calculator demo from the original appmode repo?

I was showing this off to someone with the comment of "you know, with binder you really go beyond interactive visualisations where it is impossible to work out how they were really made, you click 'edit notebook' and see how it is done" ... which kinda backfired a bit with this demo because all it does is import a demo from `ipyvolume`. And as I believe that being able to see under the bonnet and seeing something, not just shiny covers like in a modern car (to stretch this metaphor a bit too far) having something like the calculator app where you see actual code would be nice.

**Comment by choldgraf** [comment]
sounds great to me - feel free to either add it as another section of the main notebook, or to add a second notebook and provide a link in the first. Does that work?

**Comment by betatim** [comment]
I think having a second notebook is the way to go.
